import SearchBar from "./SearchBar/SearchBar";


export default function Home() {
  return (
    <>
      <SearchBar/>
      <div className="mt-16">
      <p className="text-black">Hola chavales :D</p>
      <p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>

<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>
<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>

<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>
<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>
<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>

<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>


<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>
<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>

<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>
<p className="text-black">ESTO NO ES UN JUEGO
Tu cuando juegas una partida a un videojuego y pierdes y no te enfadas y piensas que es un juego eres una mierda, eso es lo que eres, siento decirtelo, eres una basura, no eres competitivo, no eres nadie, no vas a conseguir nada en la vida, eres un perdedor, siento mucho decirtelo es la realidad, esto no es un juego, nada es un juego. Esto que está detras de la camara no es un juego, como que un juego eres imbécil tu o que? Que te pasa, como que un juego. Yo cuando pierdo una arena me jode que flipas, caundo pierdo una rbg me jode que fplias porque no es un juego. Somos 10 personas contra 10 personas, que juego es este... Preguntale a Lebron James si es un juego, maldito ignorante de mierd. Preguntale a Lebron James que igual te pega un tortazo, pero como que un juego, un juego lo será para ti que eres un nomade de mierda que no ha conseguido nada en la vida, para mi no es un juego, no te equivoques eh - xocas</p>
      </div>
    </>
  );

}
